### ISSUE TITLE
RedisStore throws error when client object is passed

### ISSUE THREAD

**Issue by jesseinvent** [wyattjoh/rate-limit-redis#41]
````
const client = createClient();
const requestLimiter = rateLimit({
  store: new RedisStore({
    client
  }),
  windowMs: 1 * 60 * 1000 * 60, // 1h
  max: 100, // Limit IP to 100 requests per hour
  message: "Request limit exceeded! try again in a short while",
});
````
Throws the following error:

``` TypeError: options.client.multi(...).incr(...).pttl is not a function ```

Any solution please?
I need to use the redis container in my docker network

**Comment by stephent** [comment]
Are you using the redis v4.x module? I'm only seeing this error since updating from 3.x to 4.x

**Comment by jesseinvent** [comment]
My redis is v4.0.1, can i please see the code solution on how you solved it?

**Comment by stephent** [comment]
Try something like this:

```
const client = createClient({ legacyMode: true });
const requestLimiter = rateLimit({
  store: new RedisStore({
    client: client,
  }),
  windowMs: 1 * 60 * 1000 * 60, // 1h
  max: 10, // Limit IP to 100 requests per hour
  message: "Request limit exceeded! try again in a short while",
});
```

Don't forget to call connect() on your client too (see https://github.com/redis/node-redis/blob/HEAD/docs/v3-to-v4.md).

**Comment by jesseinvent** [comment]
Adding ```legacyMode: true``` and calling ```.connect()``` solved the issue.

## Final code:
```
export const redisClient = () => {
  const client = createClient({
    port:  configs.REDIS_PORT,
    host: configs.REDIS_HOST,
    legacyMode: true
  });
  client.connect();
  client.on("error", (err) => logger.error(`${err.name}: ${err.message}`));

  return client;
};

```

```
const client = createClient();
const requestLimiter = rateLimit({
  store: new RedisStore({
    client
  }),
  windowMs: 1 * 60 * 1000 * 60, // 1h
  max: 10, // Limit IP to 100 requests per hour
  message: "Request limit exceeded! try again in a short while",
});
```
I hope it helps someone.

Thanks!

**Comment by stephent** [comment]
@jesseinvent I think this should be left open as an issue. This project needs updating to account for the version of client that might be passed in - right now it will attempt to create its own client against v4 of redis, but then use it as if it were a v3 client.

**Comment by jesseinvent** [comment]
@stephent reopened.

**Comment by wunderdaz** [comment]
And also because it's linked from the official Express documentation so in a perfect world it'd work out-of-the-box

**Comment by gamemaker1** [comment]
Hi,

I recently helped out with the Typescript rewrite (PR #43), which also changes how the store interacts with Redis - v3.0.0 will accept the [`sendCommand`](https://github.com/wyattjoh/rate-limit-redis#sendcommand) option instead of the `client` option.

`sendCommand` is a (sync/async) function that takes the raw command as an array of `string`s and returns the `number` or `string` response from redis. This makes the store compatible with all clients that have a public method to send raw commands to redis.

Please do take a look at [the readme for examples](https://github.com/wyattjoh/rate-limit-redis#examples) of using the store with Redis and IORedis clients. The value to be passed for `sendCommand` option is also given [here](https://github.com/wyattjoh/rate-limit-redis#sendcommand) for most Redis clients.

**Comment by gamemaker1** [comment]
Hi @epubreader,

It looks like you are using an older version of the `express-rate-limit` (version 5 or below). However, version 3 or greater of three `rate-limit-redis` works only with version 6 or above of `express-rate-limit`.

You could upgrade to version 6 of `express-rate-limit`:

```
> npm install express-rate-limit@latest
```

Hope this helps!
